package com.hwangfantasy.dao.persistence;

import com.hwangfantasy.dao.bean.ScheduledTask;
import com.hwangfantasy.dao.bean.ScheduledTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScheduledTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_task
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    long countByExample(ScheduledTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_task
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    int deleteByExample(ScheduledTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_task
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_task
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    int insert(ScheduledTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_task
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    int insertSelective(ScheduledTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_task
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    List<ScheduledTask> selectByExample(ScheduledTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_task
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    ScheduledTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_task
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") ScheduledTask record, @Param("example") ScheduledTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_task
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    int updateByExample(@Param("record") ScheduledTask record, @Param("example") ScheduledTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_task
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    int updateByPrimaryKeySelective(ScheduledTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_task
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    int updateByPrimaryKey(ScheduledTask record);
}