package com.hwangfantasy.dao.bean;

public class ScheduledTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduled_task.id
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduled_task.task_name
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduled_task.cron
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    private String cron;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduled_task.has_started
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    private Boolean hasStarted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduled_task.available
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    private Boolean available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduled_task.id
     *
     * @return the value of scheduled_task.id
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_task
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    public ScheduledTask withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduled_task.id
     *
     * @param id the value for scheduled_task.id
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduled_task.task_name
     *
     * @return the value of scheduled_task.task_name
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_task
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    public ScheduledTask withTaskName(String taskName) {
        this.setTaskName(taskName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduled_task.task_name
     *
     * @param taskName the value for scheduled_task.task_name
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduled_task.cron
     *
     * @return the value of scheduled_task.cron
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    public String getCron() {
        return cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_task
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    public ScheduledTask withCron(String cron) {
        this.setCron(cron);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduled_task.cron
     *
     * @param cron the value for scheduled_task.cron
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    public void setCron(String cron) {
        this.cron = cron == null ? null : cron.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduled_task.has_started
     *
     * @return the value of scheduled_task.has_started
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    public Boolean getHasStarted() {
        return hasStarted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_task
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    public ScheduledTask withHasStarted(Boolean hasStarted) {
        this.setHasStarted(hasStarted);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduled_task.has_started
     *
     * @param hasStarted the value for scheduled_task.has_started
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    public void setHasStarted(Boolean hasStarted) {
        this.hasStarted = hasStarted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduled_task.available
     *
     * @return the value of scheduled_task.available
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_task
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    public ScheduledTask withAvailable(Boolean available) {
        this.setAvailable(available);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduled_task.available
     *
     * @param available the value for scheduled_task.available
     *
     * @mbg.generated Wed Jun 21 16:52:11 CST 2017
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }
}